CREATE TABLE IF NOT EXISTS public.recommendation_logs (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  client_ip VARCHAR(64),
  nama VARCHAR(120),
  budget INTEGER,
  usia INTEGER,
  butuh_pendampingan BOOLEAN,
  preferensi_hotel VARCHAR(32),
  tipe_transportasi VARCHAR(32),
  destinasi_tambahan VARCHAR(32),
  paket_utama VARCHAR(64),
  alternatif_count INTEGER NOT NULL DEFAULT 0,
  status VARCHAR(24) NOT NULL DEFAULT 'success'
);

CREATE INDEX IF NOT EXISTS idx_recommendation_logs_created_at
  ON public.recommendation_logs (created_at);

CREATE INDEX IF NOT EXISTS idx_recommendation_logs_paket_utama
  ON public.recommendation_logs (paket_utama);

CREATE INDEX IF NOT EXISTS idx_recommendation_logs_status
  ON public.recommendation_logs (status);

ALTER TABLE public.recommendation_logs ENABLE ROW LEVEL SECURITY;
